esphome:
  includes:
    - dsmr_p1_sensor.h
  libraries:
    - "EspSoftwareSerial" 
  name: pulse_meterkast
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: 'MySSID'
  password: 'MyPassword'
  
# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

    sensors:
    - name: "Consumption Low Tarif Sensor"
      unit_of_measurement: kWh
      accuracy_decimals: 3
      filters:
        - multiply: 0.001
    - name: "Consumption High Tarif Sensor"
      unit_of_measurement: kWh
      accuracy_decimals: 3  
      filters:
        - multiply: 0.001
    - name: "Actual Consumption Sensor"
      unit_of_measurement: kW
      accuracy_decimals: 3      
      filters:
        - multiply: 0.001
    - name: "Instant Power Current Sensor"
      unit_of_measurement: A
      accuracy_decimals: 3      
      filters:
        - multiply: 0.001
    - name: "Instant Power Usage Sensor"
      unit_of_measurement: kW
      accuracy_decimals: 3      
      filters:
        - multiply: 0.001
    - name: "Gas Meter M3 Sensor"
      unit_of_measurement: m3
      accuracy_decimals: 3      
      filters:
        - multiply: 0.001
    - name: "Actual Tarif Sensor"
    - name: "Short Power Outages Sensor"
      accuracy_decimals: 0      
    - name: "Long Power Outages Sensor"
      accuracy_decimals: 0      
    - name: "Short Power Drops Sensor"
      accuracy_decimals: 0      
    - name: "Short Power Peaks Sensor"
      accuracy_decimals: 0
